version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"

  # npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    # For all deps ignore all major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Docker images
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
