name: nextjs.yml
on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
    tags:
      - "v*.*"
      - "v*.*.*"
  pull_request:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nextjs-build:
    name: nextjs build
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "25"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v5
        with:
          path: node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Next.js build
        id: nextjs-cache
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run ESLint
        run: npm run lint:check

      - name: Run Prettier
        run: npm run format:check

      - name: Build static
        run: npm run build:static
        env:
          BASE_PATH: /${{ github.event.repository.name }}

      - name: Upload build static artifact for github pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./out

      - name: Build standalone
        run: npm run build

      - name: Upload build standalone artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-standalone
          include-hidden-files: true
          path: |
            .next/standalone
            .next/static
          if-no-files-found: error
          retention-days: 4

  nextjs-docker:
    needs: nextjs-build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: build-standalone
      build-artifact-path: ./
      docker-file-path: ./Dockerfile
      container-image-title: "Local Lecture Buddy"
      image-name: ${{ github.repository }}

  deploy-pages:
    needs: nextjs-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
      deployments: write
    uses: ./.github/workflows/deploy-pages.yml
